<script setup>
import { computed, ref } from 'vue'
import { submitCustomRequest } from '../services/customRequest'
import { locale } from '../locale'
const sizes=['65mm','75mm','85mm','2inch','2.5inch','3inch','3.5inch','4inch','5inch','6inch','7inch'];const selectedSizes=ref([]),uses=ref([]),budgets=ref([]),video=ref([]),issue=ref('no'),email=ref(''),submitting=ref(false),message=ref('');const budgetOptions=Array.from({length:14},(_,i)=>`${(i+1)*500}`)
const t=computed(()=>locale.value==='en'?{back:'← Back to custom',title:'FPV Configuration',a:'A flight setup matched to your flying style.',b:'Practical answers for the problems you are facing.',size:'Size',use:'Use case',budget:'Budget range',video:'Video system',issue:'Is this troubleshooting instead of a new configuration?',email:'Contact email',emailHint:'Replies will be sent here',submit:'Submit FPV request',sending:'Sending...',success:'Request sent. I will get back to you soon.',optional:'Multiple choices optional',race:'Racing',freestyle:'Freestyle',cinematic:'Cinematic',relaxed:'Relaxed flying',analog:'Analog',digital:'Digital',yes:'Yes',no:'No'}:{back:'← 返回定制',title:'穿越机配置定制',a:'为你的飞行风格定制穿越机配置',b:'根据你遇到的问题，拿出最合适的解决方案',size:'尺寸',use:'用途',budget:'预算范围',video:'图传系统',issue:'是否遇到问题而非定制配置？',email:'联系邮箱',emailHint:'回复会发送到此邮箱',submit:'提交配置需求',sending:'正在发送...',success:'需求已发送，我会尽快看看。',optional:'可多选，也可不选',race:'竞速',freestyle:'花飞',cinematic:'拍摄',relaxed:'老年飞',analog:'模拟',digital:'高清',yes:'是',no:'否'})
const useOptions=computed(()=>[t.value.race,t.value.freestyle,t.value.cinematic,t.value.relaxed]);const videoOptions=computed(()=>[t.value.analog,t.value.digital,'HDzero'])
async function submit(){submitting.value=true;message.value='';try{await submitCustomRequest({service:'fpv',selections:{'尺寸 / Size':selectedSizes.value,'用途 / Use case':uses.value,'预算 / Budget':budgets.value,'图传 / Video system':video.value,'故障排查 / Troubleshooting':issue.value},contactEmail:email.value});message.value=t.value.success}catch(e){message.value=e.message}finally{submitting.value=false}}
</script>
<template><main class="page custom-service-page fpv-service-page"><RouterLink class="back-link" to="/custom">{{t.back}}</RouterLink><section class="computer-request-layout"><div class="computer-request-copy"><p class="eyebrow">Custom service / 02</p><h1>{{t.title}}</h1><p>{{t.a}}</p><p>{{t.b}}</p></div><form class="computer-request-form" @submit.prevent="submit"><fieldset><legend>{{t.size}} <small>{{t.optional}}</small></legend><div class="choice-grid"><label v-for="x in sizes" :key="x" class="choice-chip"><input v-model="selectedSizes" type="checkbox" :value="x"/><span>{{x}}</span></label></div></fieldset><fieldset><legend>{{t.use}} <small>{{t.optional}}</small></legend><div class="choice-grid"><label v-for="x in useOptions" :key="x" class="choice-chip"><input v-model="uses" type="checkbox" :value="x"/><span>{{x}}</span></label></div></fieldset><fieldset><legend>{{t.budget}} <small>￥500</small></legend><div class="choice-grid"><label v-for="x in budgetOptions" :key="x" class="choice-chip"><input v-model="budgets" type="checkbox" :value="`￥${x}`"/><span>￥{{x}}</span></label></div></fieldset><fieldset><legend>{{t.video}} <small>{{t.optional}}</small></legend><div class="choice-grid"><label v-for="x in videoOptions" :key="x" class="choice-chip"><input v-model="video" type="checkbox" :value="x"/><span>{{x}}</span></label></div></fieldset><fieldset><legend>{{t.issue}}</legend><div class="choice-grid issue-grid"><label v-for="x in [['yes',t.yes],['no',t.no]]" :key="x[0]" class="choice-chip"><input v-model="issue" type="radio" :value="x[1]"/><span>{{x[1]}}</span></label></div></fieldset><label class="contact-email-field"><span>{{t.email}} <small>{{t.emailHint}}</small></span><input v-model.trim="email" type="email" required placeholder="name@example.com"/></label><button class="computer-submit" :disabled="submitting">{{submitting?t.sending:t.submit}} <span>→</span></button><p v-if="message" class="submit-message">{{message}}</p></form></section></main></template>
