<script setup>
import { computed, ref } from 'vue'
import { submitCustomRequest } from '../services/customRequest'
import { locale } from '../locale'
const uses=ref([]),budgets=ref([]),brands=ref([]),issue=ref('no'),email=ref(''),submitting=ref(false),message=ref('')
const budgetOptions=Array.from({length:100},(_,i)=>`${i+1}000`)
const t=computed(()=>locale.value==='en'?{back:'← Back to custom',title:'PC Configuration & Tuning',a:'A suitable PC configuration based on your budget and use case.',b:'Practical answers for the problems you are facing.',use:'Use case',budget:'Budget range',brand:'Brand preference',issue:'Is this troubleshooting instead of a new configuration?',email:'Contact email',emailHint:'Replies will be sent here',submit:'Submit configuration request',sending:'Sending...',success:'Request sent. I will get back to you soon.',optional:'Multiple choices optional',game:'Gaming',work:'Work',video:'Video editing',code:'Programming',office:'Office',daily:'Daily use',any:'No preference',yes:'Yes',no:'No'}:{back:'← 返回定制',title:'电脑配置调试',a:'根据你的预算与用途，定制最合适的电脑配置方案。',b:'根据你遇到的问题，拿出最合适的解决方案。',use:'用途',budget:'预算范围',brand:'品牌偏好',issue:'是否遇到问题而非定制配置？',email:'联系邮箱',emailHint:'回复会发送到此邮箱',submit:'提交配置需求',sending:'正在发送...',success:'需求已发送，我会尽快看看。',optional:'可多选，也可不选',game:'游戏',work:'工作',video:'视频剪辑',code:'编程',office:'办公',daily:'日常',any:'都行',yes:'是',no:'否'})
const useOptions=computed(()=>[['game',t.value.game],['work',t.value.work],['video',t.value.video],['code',t.value.code],['office',t.value.office],['daily',t.value.daily]])
const brandOptions=computed(()=>['Intel','AMD','NVIDIA',t.value.any])
async function submit(){submitting.value=true;message.value='';try{await submitCustomRequest({service:'computer',selections:{'用途 / Use case':uses.value,'预算 / Budget':budgets.value,'品牌 / Brand':brands.value,'故障排查 / Troubleshooting':issue.value},contactEmail:email.value});message.value=t.value.success}catch(e){message.value=e.message}finally{submitting.value=false}}
</script>
<template><main class="page custom-service-page computer-service-page"><RouterLink class="back-link" to="/custom">{{t.back}}</RouterLink><section class="computer-request-layout"><div class="computer-request-copy"><p class="eyebrow">Custom service / 01</p><h1>{{t.title}}</h1><p>{{t.a}}</p><p>{{t.b}}</p></div><form class="computer-request-form" @submit.prevent="submit"><fieldset><legend>{{t.use}} <small>{{t.optional}}</small></legend><div class="choice-grid"><label v-for="x in useOptions" :key="x[0]" class="choice-chip"><input v-model="uses" type="checkbox" :value="x[1]"/><span>{{x[1]}}</span></label></div></fieldset><fieldset><legend>{{t.budget}} <small>￥1000</small></legend><div class="choice-grid budget-grid"><label v-for="x in budgetOptions" :key="x" class="choice-chip"><input v-model="budgets" type="checkbox" :value="`￥${x}`"/><span>￥{{x}}</span></label></div></fieldset><fieldset><legend>{{t.brand}} <small>{{t.optional}}</small></legend><div class="choice-grid"><label v-for="x in brandOptions" :key="x" class="choice-chip"><input v-model="brands" type="checkbox" :value="x"/><span>{{x}}</span></label></div></fieldset><fieldset><legend>{{t.issue}}</legend><div class="choice-grid issue-grid"><label v-for="x in [['yes',t.yes],['no',t.no]]" :key="x[0]" class="choice-chip"><input v-model="issue" type="radio" :value="x[1]"/><span>{{x[1]}}</span></label></div></fieldset><label class="contact-email-field"><span>{{t.email}} <small>{{t.emailHint}}</small></span><input v-model.trim="email" type="email" required placeholder="name@example.com"/></label><button class="computer-submit" :disabled="submitting">{{submitting?t.sending:t.submit}} <span>→</span></button><p v-if="message" class="submit-message">{{message}}</p></form></section></main></template>
