<script setup>
import { computed, onMounted, ref } from 'vue'
import { locale } from '../locale'
import { getProjects } from '../services/portfolioApi'
const image = (path) => encodeURI(`/projects/${path}`)
const text = computed(() => locale.value === 'en'
  ? { title:'Showcase', subtitle:'Projects I have been building recently', view:'VIEW', categories:[['CS','CS'],['DESIGN','DESIGN'],['FPV','FPV']], projects:[['CS / UNITY','A small game world','Hand-drawn animation, collision logic, and an endless map in a lightweight 2D world.','CS/unity游戏/Screenshot 2026-08-11 155006.png','A Unity 2D game'],['DESIGN / FABRICATION','A fully printed aircraft','Structure and material choices balanced for a 4-inch frame.','设计/4寸打印穿越机/微信图片_20260811142956_93_20.jpg','A 3D printed FPV frame'],['FPV / FIELD WORK','3-inch flight tuning','Assembly, wiring, and flight-controller tuning for a maintainable aircraft.','穿越机/穿越机组装_3inch/微信图片_20260811164206_101_20.jpg','A 3-inch FPV drone'],['CS / LOCAL AI','Cached RAG','A cache strategy for local knowledge retrieval.','CS/CacheRag/Screenshot 2026-08-11 160151.png','A local RAG interface'],['DESIGN / DAILY TOOL','Adjustable desk stand','A stable everyday stand for tablets and displays.','设计/数位屏_平板支架/微信图片_20260811142419_81_20.jpg','A 3D printed desk stand'],['FPV / ASSEMBLY','Soldering details','Clean wiring and reliable soldering form the base of a flight system.','featured-solder-detail-cw.jpg','FPV soldering details']] }
  : { title:'展示', subtitle:'我最近开始的项目', view:'查看', categories:[['CS','CS'],['设计','设计'],['穿越机','穿越机']], projects:[['CS / UNITY','小型游戏世界','手绘动画、碰撞逻辑与无限地图，在一个轻量的 2D 世界里持续发生。','CS/unity游戏/Screenshot 2026-08-11 155006.png','Unity 2D 游戏画面'],['设计 / FABRICATION','全打印飞行器','从结构设计到材料选择，为 4 寸机架寻找强度、韧性与重量之间的平衡。','设计/4寸打印穿越机/微信图片_20260811142956_93_20.jpg','3D 打印的穿越机结构'],['FPV / FIELD WORK','3 寸飞行器调试','以真实的装配、布线和飞控调试，完成一台可持续维护的 3 寸穿越机。','穿越机/穿越机组装_3inch/微信图片_20260811164206_101_20.jpg','手持的 3 寸穿越机'],['CS / LOCAL AI','即时缓存的 RAG','为本地知识库加入缓存策略，让每一次检索更贴近实际使用成本。','CS/CacheRag/Screenshot 2026-08-11 160151.png','本地 RAG 系统界面'],['设计 / DAILY TOOL','可调桌面支架','为数位屏、平板与桌面尺寸留下余量，也让日常使用足够稳定。','设计/数位屏_平板支架/微信图片_20260811142419_81_20.jpg','3D 打印的平板支架'],['FPV / ASSEMBLY','焊接细节','整洁的线路、可靠的焊点与反复检查，是飞行系统进入下一步的基础。','featured-solder-detail-cw.jpg','穿越机内部焊接细节']] })
const paths = ['/cs','/design','/fpv']
const target = (category) => category.startsWith('CS') ? '/cs' : category.startsWith('DESIGN') || category.startsWith('设计') ? '/design' : '/fpv'
const apiProjects = ref([])
const loading = ref(true)
onMounted(async () => {
  try { const featured = await getProjects({ featured: 'true', page_size: '12' }); apiProjects.value = featured.results.length ? featured.results : (await getProjects({ page_size: '12' })).results } finally { loading.value = false }
})
const showreel = computed(() => apiProjects.value.map((project) => [project.category?.name || 'PROJECT', project.title, project.summary, project.cover_image_url, project.title, project.slug]))
</script>
<template><main class="page showcase-hub"><div class="category-nav"><RouterLink v-for="(category,index) in text.categories" :key="category[0]" :to="paths[index]"><span>0{{ index + 1 }}</span><strong>{{ category[1] }}</strong><b>{{ text.view }} →</b></RouterLink></div><section class="showcase-intro"><p class="eyebrow">Project archive</p><h1>{{ text.title }}</h1><p>{{ text.subtitle }}</p></section><p v-if="loading" class="page-state">Loading projects...</p><p v-else-if="!showreel.length" class="page-state">No published projects yet.</p><section v-else class="showcase-showreel"><article v-for="(project,index) in showreel" :key="project[5]" v-reveal class="showcase-feature" :class="{ 'is-reversed': index % 2 }"><div class="feature-copy"><p>{{ project[0] }}</p><h2>{{ project[1] }}</h2><p>{{ project[2] }}</p></div><RouterLink class="feature-image" :to="`/projects/${project[5]}`"><img :src="project[3]" :alt="project[4]" /></RouterLink></article></section></main></template>
